---
- name: install postgres
  apt:
    name: "{{ item }}"
  with_items:
    - "postgresql"
    - "python-psycopg2"

- name: create database
  become_user: "postgres"
  postgresql_db:
    name: "{{ db_name }}"
    login_user: "postgres"

- name: create database user
  become_user: "postgres"
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    login_user: "postgres"
    encrypted: yes
