---
- name: server configuration
  hosts: all
  become: true
  roles:
    - "common"
    - "roles-galaxy/geerlingguy.ntp"
    - "users"

- name: database configuration
  hosts: database
  become: true
  roles:
    - "database"
